### ISSUE TITLE
Periodic event replay after enabling state persistence

### ISSUE THREAD

**Issue by dilini-muthumala** [siddhi-io/siddhi-io-file#58]
**Description:**
This issue occurred in a tailing scenario.
After enabling state persistence, all events in the file seemed to get replayed even though the file pointer is supposed to be remembered. 

**Affected Product Version:**
wso2si-1.0.0-SNAPSHOT (built from latest source)

**OS, DB, other environment details and versions:**    
Mac OS 10.13.1

**Steps to reproduce:**
1. Get a freash SI pack
2. Enable state persistence as below.
```
  # Periodic Persistence Configuration
state.persistence:
  enabled: true
  intervalInMin: 1
  revisionsToKeep: 2
  persistenceStore: org.wso2.carbon.streaming.integrator.core.persistence.FileSystemPersistenceStore
  config:
    location: siddhi-app-persistence
```
3. Create a file called `productions_json.txt` with following content and save it in a prefered location.
```
{"event":{"name":"Almond cookie","amount":100.0}}
{"event":{"name":"Baked alaska","amount":20.0}}
```
4. Deploy following siddhi app
```
    @App:name('CountProductions2')

    @App:description('Siddhi application to count the total number of orders.')

    @source(type='file', mode='LINE',
        file.uri='file:/Users/foo/resources/productions_json.txt',
        tailing='true',
        @map(type='json'))
    define stream SweetProductionStream (name string, amount double);

    @sink(type = 'log')
    define stream LogStream (totalProductions double);

    -- Following query counts the number of sweet productions.
    @info(name = 'query')
    from SweetProductionStream
    select sum(amount) as totalProductions
    insert into LogStream;
```
Note: Change `file.uri` to point to the file you created in step 3. 

You will see the count (`totalProductions`) getting incremented every minute although no change is made to the file.
